# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f1be0dae849886b8df0982626ab469230014f0fa4f158931e283ce6f196da56484c0ded5610ff41fb859f55f461c64ad3314553448f4cf0916c4ccf41c91df0

test:
  secret_key_base: 4588deccc18e3a3af22474b27ebf2ceacec3d13c7fda3fb31948978b42740e13906880934dfd9f61647b7057ed979c04339c6072b94d247e2e3d9725b96e3485

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
